volumes:
  node-modules: {}

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_PATH: /tmp/node_modules
    command:
      - sh
      - -c
      - |
        pnpm install
        pnpm dev
    tty: true
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "5173:5173"

  swagger-server:
    build:
      context: .
      dockerfile: Dockerfile.swagger
    container_name: swagger-server
    ports:
      - "8080:8080"

  graphql-server:
    build:
      context: .
      dockerfile: Dockerfile.graphql
    container_name: graphql-server
    ports:
      - "4000:4000"
