FROM node:20.12.0-bookworm
LABEL maintainer="Nyaomaru<nyaonyao0725@gmail.com>"

WORKDIR /app

RUN git clone https://github.com/nyaomaru/react_vite_swagger . && \
    npm install

EXPOSE 8080

CMD ["npm", "start"]
