FROM node:22.7
LABEL maintainer="Nyaomaru<nyaonyao0725@gmail.com>"

WORKDIR /app

RUN git clone https://github.com/nyaomaru/graphql-sample

WORKDIR /app/graphql-sample

RUN RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

EXPOSE 4000

CMD ["pnpm", "start"]
