FROM node:22.7
LABEL maintainer="Nyaomaru<nyaonyao0725@gmail.com>"

WORKDIR /app

RUN git clone https://github.com/nyaomaru/react-vite-swagger .

WORKDIR /app/react-vite-swagger

RUN npm install -g pnpm

RUN pnpm install --frozen-lockfile

EXPOSE 8080

CMD ["pnpm", "start"]
