/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CustomerRouteImport } from './routes/customer/route'
import { Route as CustomerListRouteImport } from './routes/customer/list/route'
import { Route as CustomerDetailIdRouteImport } from './routes/customer/detail/$id/route'

// Create Virtual Routes

const LoginLazyImport = createFileRoute('/login')()
const RegisterRouteLazyImport = createFileRoute('/register')()
const IndexLazyImport = createFileRoute('/')()
const CustomerEditIdRouteLazyImport = createFileRoute('/customer/edit/$id')()

// Create/Update Routes

const LoginLazyRoute = LoginLazyImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))

const RegisterRouteLazyRoute = RegisterRouteLazyImport.update({
  path: '/register',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/register/route.lazy').then((d) => d.Route),
)

const CustomerRouteRoute = CustomerRouteImport.update({
  path: '/customer',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const CustomerListRouteRoute = CustomerListRouteImport.update({
  path: '/list',
  getParentRoute: () => CustomerRouteRoute,
} as any)

const CustomerEditIdRouteLazyRoute = CustomerEditIdRouteLazyImport.update({
  path: '/edit/$id',
  getParentRoute: () => CustomerRouteRoute,
} as any).lazy(() =>
  import('./routes/customer/edit/$id/route.lazy').then((d) => d.Route),
)

const CustomerDetailIdRouteRoute = CustomerDetailIdRouteImport.update({
  path: '/detail/$id',
  getParentRoute: () => CustomerRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteLazyImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyImport
      parentRoute: typeof rootRoute
    }
    '/customer/list': {
      id: '/customer/list'
      path: '/list'
      fullPath: '/customer/list'
      preLoaderRoute: typeof CustomerListRouteImport
      parentRoute: typeof CustomerRouteImport
    }
    '/customer/detail/$id': {
      id: '/customer/detail/$id'
      path: '/detail/$id'
      fullPath: '/customer/detail/$id'
      preLoaderRoute: typeof CustomerDetailIdRouteImport
      parentRoute: typeof CustomerRouteImport
    }
    '/customer/edit/$id': {
      id: '/customer/edit/$id'
      path: '/edit/$id'
      fullPath: '/customer/edit/$id'
      preLoaderRoute: typeof CustomerEditIdRouteLazyImport
      parentRoute: typeof CustomerRouteImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  CustomerRouteRoute: CustomerRouteRoute.addChildren({
    CustomerListRouteRoute,
    CustomerDetailIdRouteRoute,
    CustomerEditIdRouteLazyRoute,
  }),
  RegisterRouteLazyRoute,
  LoginLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/customer",
        "/register",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/customer": {
      "filePath": "customer/route.tsx",
      "children": [
        "/customer/list",
        "/customer/detail/$id",
        "/customer/edit/$id"
      ]
    },
    "/register": {
      "filePath": "register/route.lazy.tsx"
    },
    "/login": {
      "filePath": "login.lazy.tsx"
    },
    "/customer/list": {
      "filePath": "customer/list/route.tsx",
      "parent": "/customer"
    },
    "/customer/detail/$id": {
      "filePath": "customer/detail/$id/route.tsx",
      "parent": "/customer"
    },
    "/customer/edit/$id": {
      "filePath": "customer/edit/$id/route.lazy.tsx",
      "parent": "/customer"
    }
  }
}
ROUTE_MANIFEST_END */
